win32 {
    HOMEDIR += $$(USERPROFILE)
}
else {
    HOMEDIR += $$(HOME)
}

INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/include"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/src"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/lib/GyverButton"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/arduinoFFT_ID1651/src"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/NTPClient_ID551"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/FastLED NeoMatrix"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/Framebuffer GFX"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/Adafruit GFX Library_ID13"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/FastLED_ID126"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/SoftwareSerial/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/SPI"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/ESPReactWifiManager"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/ESP Async WebServer/src"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/ArduinoJson_ID64/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/Hash/src"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/PubSubClient_ID89/src"
INCLUDEPATH += "$${HOMEDIR}/workplace/GyverLamp/firmware/GyverLampCpp/.pio/libdeps/nodemcu/ESPAsyncTCP_ID305/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/DNSServer/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/tools/sdk/include"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/cores/esp8266"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/tools/sdk/lwip2/include"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/variants/nodemcu"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ArduinoOTA"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/EEPROM"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266AVRISP/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266HTTPClient/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266HTTPUpdateServer/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266LLMNR"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266NetBIOS"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266SSDP"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266SdFat/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WebServer/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFiMesh/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266httpUpdate/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/Ethernet/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/GDBStub/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/LittleFS/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/SD/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/SDFS/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/SPISlave/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/Servo/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/TFT_Touch_Shield_V2"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/Ticker/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/Wire"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoespressif8266/libraries/esp8266/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/xtensa-lx106-elf"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/toolchain-xtensa/lib/gcc/xtensa-lx106-elf/4.8.2/include"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/toolchain-xtensa/lib/gcc/xtensa-lx106-elf/4.8.2/include-fixed"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/tool-unity"

DEFINES += "PLATFORMIO=40201"
DEFINES += "ESP8266"
DEFINES += "ARDUINO_ARCH_ESP8266"
DEFINES += "ARDUINO_ESP8266_NODEMCU"
DEFINES += "PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x"
DEFINES += "PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH_LOW_FLASH"
DEFINES += "VTABLES_IN_FLASH"
DEFINES += "F_CPU=80000000L"
DEFINES += "__ets__"
DEFINES += "ICACHE_FLASH"
DEFINES += "ARDUINO=10805"
DEFINES += "ARDUINO_BOARD=&quot;PLATFORMIO_NODEMCUV2&quot;"
DEFINES += "FLASHMODE_DIO"
DEFINES += "LWIP_OPEN_SRC"
DEFINES += "NONOSDK22x_190703=1"
DEFINES += "TCP_MSS=1460"
DEFINES += "LWIP_FEATURES=0"
DEFINES += "LWIP_IPV6=0"

OTHER_FILES += platformio.ini

SOURCES += src/EffectsManager.cpp
HEADERS += src/EffectsManager.h
SOURCES += src/GyverTimer.cpp
HEADERS += src/GyverTimer.h
SOURCES += src/LampWebServer.cpp
HEADERS += src/LampWebServer.h
SOURCES += src/LocalDNS.cpp
HEADERS += src/LocalDNS.h
SOURCES += src/main.cpp
SOURCES += src/MqttClient.cpp
HEADERS += src/MqttClient.h
SOURCES += src/MyMatrix.cpp
HEADERS += src/MyMatrix.h
SOURCES += src/Settings.cpp
HEADERS += src/Settings.h
SOURCES += src/Spectrometer.cpp
HEADERS += src/Spectrometer.h
SOURCES += src/effects/Effect.cpp
HEADERS += src/effects/Effect.h
SOURCES += src/effects/basic/ClockEffect.cpp
HEADERS += src/effects/basic/ClockEffect.h
SOURCES += src/effects/basic/ClockHorizontal1Effect.cpp
HEADERS += src/effects/basic/ClockHorizontal1Effect.h
SOURCES += src/effects/basic/ClockHorizontal2Effect.cpp
HEADERS += src/effects/basic/ClockHorizontal2Effect.h
SOURCES += src/effects/basic/ClockHorizontal3Effect.cpp
HEADERS += src/effects/basic/ClockHorizontal3Effect.h
SOURCES += src/effects/basic/ColorEffect.cpp
HEADERS += src/effects/basic/ColorEffect.h
SOURCES += src/effects/basic/ColorsEffect.cpp
HEADERS += src/effects/basic/ColorsEffect.h
SOURCES += src/effects/basic/DiagonalRainbowEffect.cpp
HEADERS += src/effects/basic/DiagonalRainbowEffect.h
SOURCES += src/effects/basic/FireEffect.cpp
HEADERS += src/effects/basic/FireEffect.h
SOURCES += src/effects/basic/HorizontalRainbowEffect.cpp
HEADERS += src/effects/basic/HorizontalRainbowEffect.h
SOURCES += src/effects/basic/LightersEffect.cpp
HEADERS += src/effects/basic/LightersEffect.h
SOURCES += src/effects/basic/MatrixEffect.cpp
HEADERS += src/effects/basic/MatrixEffect.h
SOURCES += src/effects/basic/SnowEffect.cpp
HEADERS += src/effects/basic/SnowEffect.h
SOURCES += src/effects/basic/SparklesEffect.cpp
HEADERS += src/effects/basic/SparklesEffect.h
SOURCES += src/effects/basic/StarfallEffect.cpp
HEADERS += src/effects/basic/StarfallEffect.h
SOURCES += src/effects/basic/VerticalRainbowEffect.cpp
HEADERS += src/effects/basic/VerticalRainbowEffect.h
SOURCES += src/effects/noise/CloudNoiseEffect.cpp
HEADERS += src/effects/noise/CloudNoiseEffect.h
SOURCES += src/effects/noise/ForestNoiseEffect.cpp
HEADERS += src/effects/noise/ForestNoiseEffect.h
SOURCES += src/effects/noise/LavaNoiseEffect.cpp
HEADERS += src/effects/noise/LavaNoiseEffect.h
SOURCES += src/effects/noise/MadnessNoiseEffect.cpp
HEADERS += src/effects/noise/MadnessNoiseEffect.h
SOURCES += src/effects/noise/NoiseEffect.cpp
HEADERS += src/effects/noise/NoiseEffect.h
SOURCES += src/effects/noise/OceanNoiseEffect.cpp
HEADERS += src/effects/noise/OceanNoiseEffect.h
SOURCES += src/effects/noise/PlasmaNoiseEffect.cpp
HEADERS += src/effects/noise/PlasmaNoiseEffect.h
SOURCES += src/effects/noise/RainbowNoiseEffect.cpp
HEADERS += src/effects/noise/RainbowNoiseEffect.h
SOURCES += src/effects/noise/RainbowStripeNoiseEffect.cpp
HEADERS += src/effects/noise/RainbowStripeNoiseEffect.h
SOURCES += src/effects/noise/ZebraNoiseEffect.cpp
HEADERS += src/effects/noise/ZebraNoiseEffect.h
SOURCES += src/effects/sound/SoundEffect.cpp
HEADERS += src/effects/sound/SoundEffect.h
SOURCES += src/effects/sound/SoundStereoEffect.cpp
HEADERS += src/effects/sound/SoundStereoEffect.h
